version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: typescript
    versions:
    - ">= 3.6.a, < 3.7"
  - dependency-name: typescript
    versions:
    - ">= 3.7.a, < 3.8"
  - dependency-name: "@bazel/typescript"
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.2.1
    - 3.2.2
    - 3.2.3
    - 3.3.0
    - 3.4.0
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: "@bazel/ibazel"
    versions:
    - 0.14.0
    - 0.15.6
    - 0.15.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: wait-on
    versions:
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: typescript
    versions:
    - 3.9.7
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: "@nestjs/common"
    versions:
    - 6.11.11
